"""
Syncs config/config.yaml to frontend and backend config files.
WRITTEN BY CLAUDE

TODO: This file is kinda shit, but not worth changing.
Reasons:
1. For the backend it should just read the YAML directly and expose each field.
2. For the frontend it should compute the backend's endpoint instead of storing its own.
3. Set data should also be included in the config.

Usage:
    python scripts/sync_config.py
"""
import yaml

CONFIG_PATH = "config/config.yaml"
FRONTEND_CONFIG_PATH = "frontend/tft-frontend/src/Config.tsx"
BACKEND_CONFIG_PATH = "tft/config.py"


def read_config():
    with open(CONFIG_PATH, "r") as f:
        return yaml.safe_load(f)


def write_frontend_config(config):
    # Extract host from frontend endpoint, combine with backend port.
    frontend_endpoint = config["frontend"]["endpoint"]
    # Parse out the host (e.g., "http://172.30.111.252:9001" -> "172.30.111.252")
    host = frontend_endpoint.split("://")[1].split(":")[0]
    backend_port = config["backend"]["port"]
    endpoint = f"http://{host}:{backend_port}"
    tft_set = config["tft"]["set"]

    content = f'''
    // DO NOT EDIT THIS FILE, IT IS GENERATED BY sync_config.py SCIPT.
    export const ENDPOINT = '{endpoint}'\n
    export const TFT_SET = '{tft_set}'\n
    '''

    with open(FRONTEND_CONFIG_PATH, "w") as f:
        f.write(content)
    print(f"Wrote frontend config to {FRONTEND_CONFIG_PATH}")


def write_backend_config(config):
    backend = config["backend"]
    files = config["files"]
    tft = config["tft"]

    content = f'''
"""
DO NOT EDIT THIS FILE, IT IS GENERATED BY sync_config.py SCIPT.
"""
import yaml

# Server configs.
DB = "{backend['db']}"
IP = "{backend['ip']}"
PORT = {backend['port']}

# Alias configs.
CHAMP_ALIAS_FILE = "{files['champ_alias']}"
ITEM_ALIAS_FILE = "{files['item_alias']}"
TRAIT_ALIAS_FILE = "{files['trait_alias']}"

# Data configs.
TFT_SET = "{tft["set"]}"
CLUSTER_ID = {tft["cluster_id"]}
DAYS = {tft["days"]}
RANK = {tft["ranks"]}
'''

    with open(BACKEND_CONFIG_PATH, "w") as f:
        f.write(content)
    print(f"Wrote backend config to {BACKEND_CONFIG_PATH}")


if __name__ == "__main__":
    config = read_config()
    write_frontend_config(config)
    write_backend_config(config)
    print("Config sync complete!")
