
"""
DO NOT EDIT THIS FILE, IT IS GENERATED BY sync_config.py SCIPT.
"""
import yaml

# Server configs.
DB = "mongodb://127.0.0.1:32769/?directConnection=true"
IP = "0.0.0.0"
PORT = 10000

# Alias configs.
CHAMP_ALIAS_FILE = "config/champ_aliases.csv"
ITEM_ALIAS_FILE = "config/item_aliases.csv"
TRAIT_ALIAS_FILE = "config/trait_aliases.csv"

# Data configs.
TFT_SET = "TFTSet16"
CLUSTER_ID = 386
DAYS = 1
RANK = ['CHALLENGER', 'DIAMOND', 'EMERALD', 'MASTER', 'PLATINUM']
